/**
 * Type definitions for external exercise data sources
 * ExerciseDB and Free Exercise DB
 */

// ExerciseDB data structure (from GitHub open source dataset)
export interface ExerciseDBExercise {
  id: string;
  name: string;
  bodyPart: string;
  equipment: string;
  gifUrl: string;
  target: string;
  secondaryMuscles: string[];
  instructions: string[];
}

// Free Exercise DB data structure
export interface FreeExerciseDBExercise {
  id: string;
  name: string;
  force?: string | null;
  level: string;
  mechanic?: string | null;
  equipment?: string | null;
  primaryMuscles: string[];
  secondaryMuscles: string[];
  instructions: string[];
  category: string;
  images: string[];
}

// Our internal exercise schema (matches Supabase table)
export interface InternalExercise {
  id?: string; // UUID generated by Supabase
  name: string;
  slug: string;
  muscle_group: string;
  equipment: string; // Required: barbell, dumbbell, cable, machine, bodyweight, band
  category: string; // Required: compound, isolation, cardio, stretch
  instructions: string | null;
  form_tips: string[] | null;
  image_url: string | null;
  gif_url: string | null;
  source: "library" | "exercisedb" | "free-exercise-db" | "custom";
  source_exercise_id: string | null;
}

// Muscle group mappings
export const EXERCISEDB_MUSCLE_MAP: Record<string, string> = {
  "chest": "chest",
  "back": "back",
  "shoulders": "shoulders",
  "upper arms": "arms",
  "lower arms": "arms",
  "waist": "core",
  "cardio": "cardio",
  "upper legs": "legs",
  "lower legs": "legs",
  "neck": "shoulders",
};

export const FREE_EXERCISE_DB_MUSCLE_MAP: Record<string, string> = {
  "chest": "chest",
  "back": "back",
  "shoulders": "shoulders",
  "biceps": "arms",
  "triceps": "arms",
  "forearms": "arms",
  "abdominals": "core",
  "quadriceps": "legs",
  "hamstrings": "legs",
  "calves": "legs",
  "glutes": "legs",
  "adductors": "legs",
  "abductors": "legs",
  "middle back": "back",
  "lats": "back",
  "lower back": "back",
  "traps": "back",
  "neck": "shoulders",
};

// Equipment mappings (maps to database enum: barbell, dumbbell, cable, machine, bodyweight, band)
export const EQUIPMENT_MAP: Record<string, string> = {
  "barbell": "barbell",
  "dumbbell": "dumbbell",
  "dumbbells": "dumbbell",
  "cable": "cable",
  "machine": "machine",
  "body weight": "bodyweight",
  "body only": "bodyweight",
  "bodyweight": "bodyweight",
  "assisted": "machine",
  "band": "band",
  "bands": "band",
  "resistance band": "band",
  "medicine ball": "machine", // Closest match
  "kettlebell": "dumbbell", // Similar to dumbbell
  "stability ball": "machine", // Closest match
  "foam roll": "bodyweight", // Recovery/mobility
  "ez barbell": "barbell",
  "e-z curl bar": "barbell",
  "trap bar": "barbell",
  "olympic barbell": "barbell",
  "weighted": "dumbbell", // Generic weight
  "rope": "cable",
  "leverage machine": "machine",
  "sled machine": "machine",
  "smith machine": "machine",
  "exercise ball": "machine",
  "none": "bodyweight",
  "other": "bodyweight", // Default for unknown
  "": "bodyweight",
};

// Category inference based on exercise characteristics
// Maps to database enum: compound, isolation, cardio, stretch
export function inferCategory(
  exerciseName: string,
  equipment: string,
  muscleGroup: string
): "compound" | "isolation" | "cardio" | "stretch" {
  const nameLower = exerciseName.toLowerCase();

  // Cardio exercises
  if (nameLower.includes("run") || nameLower.includes("jump") ||
      nameLower.includes("sprint") || nameLower.includes("rowing") ||
      nameLower.includes("cycling") || muscleGroup === "cardio") {
    return "cardio";
  }

  // Stretching/mobility (changed from "mobility" to "stretch" to match enum)
  if (nameLower.includes("stretch") || nameLower.includes("foam roll") ||
      nameLower.includes("mobility")) {
    return "stretch";
  }

  // Compound movements (multi-joint)
  const compoundKeywords = [
    "squat", "deadlift", "press", "row", "pull-up", "chin-up",
    "dip", "lunge", "clean", "snatch", "push-up", "bench",
  ];

  if (compoundKeywords.some(keyword => nameLower.includes(keyword))) {
    return "compound";
  }

  // Default to isolation
  return "isolation";
}

// Slug generation (URL-safe name)
export function generateSlug(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, "")
    .trim()
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-");
}
