-- ============================================================================
-- Migration 071: Training Programs
-- Multi-week periodized training programs generated by AI.
-- ============================================================================

CREATE TABLE training_programs (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  name TEXT NOT NULL,
  description TEXT,
  goal TEXT NOT NULL,
  weeks INTEGER NOT NULL CHECK (weeks BETWEEN 4 AND 12),
  days_per_week INTEGER NOT NULL CHECK (days_per_week BETWEEN 2 AND 6),
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'active', 'completed', 'abandoned')),
  current_week INTEGER DEFAULT 1,
  current_day INTEGER DEFAULT 1,
  program_data JSONB NOT NULL,
  started_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

CREATE INDEX idx_training_programs_user_status
  ON training_programs(user_id, status);

ALTER TABLE training_programs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users manage own programs"
  ON training_programs FOR ALL
  TO authenticated
  USING (auth.uid() = user_id);
